name: check
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          stable: "false"
          go-version: "^1.17" # The Go version to download (if necessary) and use.

      - name: Install dependencies
        run: go get -u golang.org/x/lint/golint

      - name: Run tests
        run: go test -v .

      - name: Run vet
        run: go vet .
      